// All words on the site that are not survey items or domain definitions.
// Placeholders in {braces} are filled in by the page; keep them when editing.

export default {
  siteTitle: 'Innovation capability framework',
  siteSubtitle: 'Prototype',
  mockLabel: 'Mock data',
  footer: 'Prototype of the draft innovation capability framework. Your answers stay in this browser. Everything except your own answers is generated for illustration.',

  nav: {
    next: 'Continue',
    back: 'Back',
    startSurvey: 'Start the survey',
    preview: 'Preview with sample answers',
    previewHint: 'Skip to the results with a made-up set of answers.',
    restart: 'Start again',
    retake: 'Change my answers',
    stepOf: 'Step {n} of {total}',
  },

  orientation: [
    {
      title: 'A shared framework for innovation capability',
      lead: 'The framework describes what it takes for good ideas to become changes that are in use at the IB. It has four parts.',
      body: [
        'Two parts are capabilities: what a person does when innovating, and how a team works with ideas together. One is climate: the conditions a manager and the IB create. The last is performance: what comes of it.',
        'Someone can be strong on every individual capability, but if the conditions do not support innovation, those capabilities may not show up in practice.',
      ],
    },
    {
      title: 'How it is measured',
      lead: 'Three sources, each suited to what it measures.',
      sources: [
        { title: 'Annual survey', subtitle: 'All IB staff, once a year, 43 items', text: 'Scores each individual domain, the three team capabilities, the manager and organisation climate, co-creation, and self-reported outputs.',
          boxes: [
            { tone: 'a', text: 'A1 to A6 Individual capabilities' },
            { tone: 'b', text: 'B1 to B3 Team capabilities' },
            { tone: 'c', text: 'C1, C2 Innovation climate' },
            { tone: 'd', text: 'D1 Output items (self-reported)' },
            { tone: 'neutral', text: 'Co-creation items (A2, A5, C1)' },
          ] },
        { title: 'Skill assessment', subtitle: 'Per intervention: before, after, three months', text: 'A single confidence item for the skill a session teaches, and whether people have used it since.',
          boxes: [
            { tone: 'skill', text: 'Task-specific self-efficacy', note: 'self-confidence on the skill taught' },
            { tone: 'skill', text: 'Skill used since' },
          ] },
        { title: 'Innovation pipeline records', subtitle: 'Every proposal, from intake to use', text: 'Which proposals are decided and put into use, and how long each step takes.',
          boxes: [
            { tone: 'd', text: 'D1 Innovation outputs' },
            { tone: 'd', text: 'D2 Time to decision' },
            { tone: 'd', text: 'D3 Time to implement' },
          ] },
      ],
    },
    {
      title: 'What you are about to do',
      lead: 'You will answer the annual survey as one member of staff would, then see what it produces.',
      steps: [
        { title: 'Answer 43 statements', text: 'About ten minutes. Each is on a five-point scale from fully disagree to fully agree. They come in thirteen short groups, one per scale, so you can see the structure as you go.' },
        { title: 'See three views of the results', text: 'Your own profile; what your manager would see about the team; and what the IB would see across offices, alongside the pipeline and a skills workshop.' },
      ],
      role: 'For this prototype you are a senior expert in the Education Innovation department of the Education office. Your manager is the Director of Education Innovation.',
      privacy: 'Your answers are kept only in this browser and are never sent anywhere. Everyone else in the results is generated.',
    },
  ],

  survey: {
    progress: '{answered} of {total} answered',
    sectionOf: 'Group {n} of {total}',
    next: 'Next group',
    back: 'Previous group',
    finish: 'See my results',
    incomplete: 'Answer every statement in this group to continue.',
    minLabel: 'Fully disagree',
    maxLabel: 'Fully agree',
    // Shown above each group, by who the statements are about.
    about: {
      self: 'About you and your own work.',
      team: 'About your own team.',
      manager: 'About the manager you report to.',
      organisation: 'About the IB as a whole.',
    },
  },

  // Used by "Preview with sample answers": one value per item, in document order within each scale.
  sampleAnswers: {
    A1: [4, 4, 5],
    A2: [5, 5, 4],
    A3: [4, 5, 4, 4],
    A4: [3, 2, 3],
    A5: [4, 4, 3],
    A6: [4, 3, 4, 4],
    D1: [3, 3, 4],
    C1: [4, 4, 3, 5, 3],
    C2: [3, 2, 2],
    CC: [4, 4, 3],
    B1: [4, 3, 4],
    B2: [3, 4, 3],
    B3: [3, 3, 4],
  },

  results: {
    tabs: { you: 'You', team: 'Your team', ib: 'The IB' },
    tabsLabel: 'Results views',
    tabHints: { you: 'Employee view', team: 'Manager view', ib: 'Organisation view' },
    needAnswers: {
      title: 'Your results appear once you have answered the survey',
      text: 'Answer the 43 statements, or preview the results with a made-up set of answers.',
    },
    sampleNotice: 'You are looking at sample answers, not your own.',
    mockBanner: 'Generated data for a fictional IB of 910 staff, with a fixed seed. No real person’s responses are shown.',
    scaleNote: 'Scores run from 1 (fully disagree) to 5 (fully agree).',
    ibBaseline: 'IB (mock)',
    officeBaseline: 'Education office (mock)',
    you: 'You',

    // Comparison wording, chosen by the gap between a score and the IB figure.
    compare: {
      threshold: 0.3,
      above: 'above the IB',
      below: 'below the IB',
      close: 'close to the IB',
      rateAbove: 'more highly',
      rateBelow: 'less highly',
      rateClose: 'about the same',
      ibValue: 'IB {value}',
    },

    employee: {
      title: 'Your innovation profile',
      intro: 'This is how you describe your own innovation work, set against the IB as a whole. It is a starting point for a conversation, not a rating.',
      strongestTitle: 'Where you are strongest',
      strongest: 'Your answers put {domain} first. {explain}',
      developTitle: 'Where there is most room to grow',
      develop: 'Your answers put {domain} last. {explain}',
      developSkills: 'The skills the department builds here: {skills}.',
      capabilitiesTitle: 'Your individual capabilities',
      capabilitiesIntro: 'What you do when innovating, from generating an idea to seeing it in use, plus how much you work with the people an idea affects and how far your ideas are already in use.',
      teamTitle: 'How you see your team',
      teamIntro: 'How your team handles ideas together. These describe the team, not you.',
      climateTitle: 'How you see the conditions around you',
      climateIntro: 'What your manager and the IB do to make innovation possible.',
      climateReading: 'Compared with colleagues across the IB, you rate your manager {c1word} and the IB itself {c2word}.',
      legendYou: 'Your score',
      legendIb: 'IB average (mock)',
    },

    manager: {
      title: 'Education Innovation: team view',
      intro: 'What the Director of Education Innovation would see about their own team. Individual answers are never shown; group results appear only where at least {min} people responded.',
      viewerLine: 'Viewed as {name}, {title}.',
      c1Title: 'Conditions you create (C1)',
      c1Intro: 'How your seven senior experts rate the conditions you create for new ideas, against the Education office and the IB.',
      c1Respondents: 'Based on {n} responses.',
      c1Leaders: 'Your C1 score among IB leaders with at least {min} respondents',
      c1LeadersNote: 'Each mark is one leader. Yours is highlighted.',
      practicesTitle: 'The practices behind this score',
      teamTitle: 'How your team works with ideas (B1 to B3)',
      teamIntro: 'Your team’s view of how it handles ideas together, against the IB.',
      profileTitle: 'Your team’s capability profile',
      profileIntro: 'The average of your team’s individual scores, anonymised.',
      suppressed: 'Not shown: fewer than {min} people responded.',
      legendTeam: 'Your team',
      teamBar: 'Your team (n={n})',
    },

    organisation: {
      title: 'The IB: organisation view',
      intro: 'Innovation capability and climate across the IB and by office, what came through the innovation pipeline in the last year, and how one skills workshop landed.',
      surveyTitle: 'Survey results by office',
      surveyIntro: 'Average score on each scale. Shading shows how far an office sits from the IB figure.',
      respondents: 'Respondents',
      respondentsShort: 'n',
      ibRow: 'IB',
      heatLegend: 'Green shading means above the IB figure and red means below; the darker the shade, the bigger the gap. The small figure under each score gives the gap.',
      heatGroups: { A: 'Individual', D: 'Performance', CC: 'Co-creation', B: 'Team', C: 'Climate' },
      scrollHint: 'Scroll sideways to see every scale.',
      performanceTitle: 'Innovation performance',
      performanceIntro: 'Every proposal that entered the pipeline between September 2025 and August 2026.',
      kpis: {
        proposals: 'Proposals',
        inUse: 'In use (D1)',
        timeToDecision: 'Median time to decision (D2)',
        timeToImplement: 'Median time to implement (D3)',
        days: '{n} days',
        open: '{n} still open',
      },
      decisionsTitle: 'Decisions',
      durationsTitle: 'How long proposals took',
      durationsIntro: 'Each mark is one proposal. The line marks the median.',
      outputsTitle: 'Innovation outputs: proposals now in use',
      outputsColumns: { title: 'Proposal', change: 'What changed', novelty: 'Novelty', horizon: 'Horizon', decision: 'To decision', implement: 'To implement' },
      pipelineTitle: 'All proposals',
      pipelineColumns: { office: 'Office', status: 'Status', submitted: 'Submitted' },
      decisionLabels: { go: 'Go', stop: 'Stop', park: 'Park', awaiting: 'Awaiting decision' },
      medianDays: 'Median {n} days',
      outputCard: '{novelty}, {horizon}, {decision} days to decision, {implement} days to implement',
      skillsUsed: '{used} of {total} have run a discovery interview since',
      selfReported: 'Self-reported outputs (survey D1): IB average {score} from {n} respondents, which also counts ideas that never went through the pipeline.',
      skillsTitle: 'Skill assessment: discovery interviews workshop',
      skillsIntro: 'Fourteen participants answered the same confidence item before the half-day workshop, straight after it, and three months later.',
      skillsPreToPost: 'Did the session raise confidence? From {pre} to {post}.',
      skillsPreToFollow: 'Did it change what people do? Confidence at three months {follow}, and {used} of {total} have run a discovery interview since.',
      skillsPoints: { pre: 'Before', post: 'Straight after', followUp: 'Three months' },
      figureCaption: 'When the self-efficacy item is asked (Figure 3 in the framework document).',
    },
  },
};
